"""Export packager service for Rotoscope Studio.

Bundles all per-job artifacts (frames, masks, preview,
metadata) into a single zip archive that the user can
download.
"""
import os
import zipfile
import pathlib
from datetime import datetime, timezone
from typing import Any, Dict

import app.config as _config
from app.services import job_store


EXPORT_FILENAME = 'rotoscope_export.zip'


def _build_metadata_text(job: Dict) -> str:
    """Build a human-readable metadata string for the export archive."""
    lines = [
        'Rotoscope Studio Export',
        'Job ID: ' + str(job.get('job_id', '')),
        'Source file: ' + str(job.get('file_name', '')),
        'Workflow: ' + str(job.get('workflow', '')),
        'Subject: ' + str(job.get('subject', '')),
        'Exported at: ' + datetime.now(timezone.utc).isoformat() + 'Z',
        'Frames folder: frames/',
        'Masks folder: masks/',
        'Previews folder: previews/',
        '',
        'This export was generated by Rotoscope Studio.',
        ]
    return '\n'.join(lines)


def package_export(job_id: str) -> str:
    """Bundle all artifacts for a job into a single zip file.

    The zip includes the original frames, the generated masks, a preview
    image, a job.json metadata file, and a human-readable metadata txt.

    Returns the path to the generated zip file."""
    job = job_store.get_job(job_id)
    if not job:
        raise FileNotFoundError(f'Job not found: {job_id}')
    frames_dir = _config.frames_dir(job_id)
    masks_dir = _config.masks_dir(job_id)
    previews_dir = _config.previews_dir(job_id)
    exports_dir = _config.exports_dir(job_id)
    exports_dir.mkdir(parents=True, exist_ok=True)
    zip_path = exports_dir / EXPORT_FILENAME
    # Remove any existing export file from a previous run.
    if zip_path.is_file():
        try:
            zip_path.unlink()
        except OSError:
            pass
    with zipfile.ZipFile(str(zip_path), 'w', zipfile.ZIP_DEFLATED) as zf:
        # Frames: original frames.
        if frames_dir.is_dir():
            for fn in sorted(os.listdir(frames_dir)):
                zf.write(frames_dir / fn, 'frames/' + fn)
        # Masks: generated masks.
        if masks_dir.is_dir():
            for fn in sorted(os.listdir(masks_dir)):
                zf.write(masks_dir / fn, 'masks/' + fn)
        # Previews: sprite sheet and pairs.
        if previews_dir.is_dir():
            for fn in sorted(os.listdir(previews_dir)):
                zf.write(previews_dir / fn, 'previews/' + fn)
        # Job metadata.
        job_json_path = _config.JOBS_DIR / job_id / 'job.json'
        if job_json_path.is_file():
            zf.write(job_json_path, 'job.json')
        # Human-readable metadata.
        zf.writestr('metadata.txt', _build_metadata_text(job))
    return str(zip_path)


def get_export_path(job_id: str) -> str:
    """Return the path to the generated export zip."""
    return str(_config.exports_dir(job_id) / EXPORT_FILENAME)


def list_exports(job_id: str) -> Dict:
    """Return a dict describing the existing export archives for the job."""
    exports_dir = _config.exports_dir(job_id)
    zip_path = exports_dir / EXPORT_FILENAME
    return {'zip_path': str(zip_path) if zip_path.is_file() else None, 'size_bytes': zip_path.stat().st_size if zip_path.is_file() else 0}
